# Generated by Django 4.2.16 on 2024-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('idbanner', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('posicion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banner',
            },
        ),
    ]
