# Generated by Django 4.2.16 on 2024-11-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bancopreguntas',
            },
        ),
        migrations.CreateModel(
            name='BancoRespuestas',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancopreguntas')),
            ],
            options={
                'verbose_name': 'bancorespuestas',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('idplan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'planestudios',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('idplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios')),
            ],
            options={
                'verbose_name': 'cursos',
                'unique_together': {('idcurso', 'idplan')},
            },
        ),
        migrations.CreateModel(
            name='BancoResultados',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancopreguntas')),
                ('idrespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancorespuestas')),
            ],
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cursos'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios'),
        ),
    ]
